spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  # H2 콘솔 활성화 (필요시)
  h2:
    console:
      enabled: true
      path: /h2-console

# 기본 서버 포트 (8080이 아닌 다른 포트를 원하면 변경 가능)
server:
  port: 8080

# 로그 설정 (선택 사항)
logging:
  level:
    root: INFO
    org.springframework: DEBUG