services:
  order-service:
    image: order-service:1.0
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_BASE_URL: http://zipkin-zipkin-1:9411
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-server:3306/mydb
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-discovery:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-zipkin-1:9411/api/v2/spans
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network