services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: test1357
      MARIADB_USER: example-user
      MARIADB_PASSWORD: test1357
      MARIADB_DATABASE: mydb
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network