FROM ubuntu
CMD ["echo", "hello"]

# exec form : 쉘을 통하지 않고 명령어를 직접 실행 (recommanded), 
#             쉘에서 제공하는 기능을 사용할 수 없음 (ex: CMD ["echo", "$HOME"])
#                                 사용하고 싶다면? CMD ["/bin/bash", "-c", "echo $HOME"]
# CMD  [ "./hello.out" ]

# shell form : 쉘 명령어를 사용하는 일반적인 명령어 실행 방식
# CMD ./hello.out