spring:
  application:
    name: config-server
  profiles:
    active:
      # native : exist in local file storage (external storage X)
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            # path for configuration file
            - classpath:/board
            - classpath:/discovery
            - classpath:/license
            - classpath:/organization
            - classpath:/gateway
          # - file:///tmp/config
          # git:
          # uri: https://github.com/wdd1016/InspireCamp.git
          # search-paths: SpringCloud/config

server:
  port: 8071

encrypt:
  # 암호화에 사용하는 비밀키 (임의의 값을 사용)
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
