server:
  port: 8888

spring:
  profiles:
    active: git
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/git-local-repo
        # search-locations: file:///C://work//git-local-repo
        git: #default
          # uri: https://github.com/joneconsulting/spring-cloud-config
          # git에 커밋할때마다 변화를 감지하여 서버 업데이트
          uri: file:///tmp/git-local-repo
          default-label: main
        # username: <github-id>
        # password: <gihub-accessToken>
        bootstrap: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
