server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/git-local-repo
        # search-locations: file:///C://work//git-local-repo
        git: #default
          # remote repo 가 변할때 마다 감지
          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master

          # git에 커밋할때마다 변화를 감지하여 config 서버 업데이트
          # uri: file:///tmp/git-local-repo
        # username: <github-id>
        # password: <gihub-accessToken>
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
