services:
  mysql:
    image: mysql:8.0
    ports:
      - "4406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: springboot
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
  springboot:
    depends_on:
      - mysql
    image: backend:0.0.1-SNAPSHOT
    ports:
      - "9090:8080"
    volumes:
      - ./backend/uploads:/workspace/uploads
  react:
    depends_on:
      - springboot
    image: board-app:v3
    ports:
      - "90:80"